### PR TITLE
fix: handle maps with `__struct__` key

### LINKED ISSUE #57: CaseClauseError with return type of Ecto.Changeset.t()
I'm using the latest commit on the `master` branch.

I have a function in a behaviour that returns an Ecto Changeset.  If I attempt to wrap this function with `Hammox.protect` while testing it, I get the following error message and stack trace. I've reproduced this error in a separate repo that I can publish somewhere if it would be helpful; important extracts are below.

I'm happy to try to help track this down, but I'm not sure of the best way to do that. Tips welcome!

```
     ** (CaseClauseError) no case clause matching: [{:type, 441, :map_field_exact, [{:atom, 0, :__struct__}, {:type, 441, :atom, []}]}]
     stacktrace:
       (hammox 0.2.5) lib/hammox/type_engine.ex:346: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:12: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:11: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:12: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:11: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:375: anonymous fn/3 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
       (stdlib 3.11.1) maps.erl:232: :maps.fold_1/3
       (elixir 1.10.0) lib/enum.ex:2127: Enum.map/2
       (hammox 0.2.5) lib/hammox/type_engine.ex:374: anonymous fn/2 in Hammox.TypeEngine.match_type/2
       (elixir 1.10.0) lib/enum.ex:3686: Enumerable.List.reduce/3
       (elixir 1.10.0) lib/enum.ex:2161: Enum.reduce_while/3
       (hammox 0.2.5) lib/hammox/type_engine.ex:372: Hammox.TypeEngine.match_type/2
       (hammox 0.2.5) lib/hammox.ex:359: Hammox.match_return_value/2
       (hammox 0.2.5) lib/hammox.ex:327: Hammox.match_call/3
       (hammox 0.2.5) lib/hammox.ex:311: anonymous fn/4 in Hammox.check_call/3
```

Here are the behavior and implementation:

```elixir
defmodule HammoxTest.Friends.Impl do
  alias HammoxTest.Friends.Person

  @callback change_person(Person.t(), map()) :: Ecto.Changeset.t()
end

defmodule HammoxTest.Friends do
  alias HammoxTest.Friends.{Impl, Person}

  @behaviour Impl

  @impl Impl
  def change_person(%Person{} = person, attrs \\ %{}) do
    person
    |> Person.changeset(attrs)
  end
end

defmodule HammoxTest.Friends.Person do
  use Ecto.Schema

  @type t :: %__MODULE__{
          first_name: String.t() | nil,
          last_name: String.t() | nil,
          age: integer() | nil
        }

  schema "people" do
    field(:first_name, :string)
    field(:last_name, :string)
    field(:age, :integer)
  end

  def changeset(person, attrs \\ %{}) do
    person
    |> Ecto.Changeset.cast(attrs, [:first_name, :last_name, :age])
    |> Ecto.Changeset.validate_required([:first_name, :last_name])
  end
end
```

And here is the test:
```elixir
defmodule HammoxTest.FriendsTest do
  use ExUnit.Case

  import Hammox

  alias HammoxTest.Friends
  alias HammoxTest.Friends.{Impl, Person}

  test "can I type-check a changeset?" do
    change_person_2 = protect({Friends, :change_person, 2}, Impl)

    changeset = change_person_2.(%Person{}, %{age: 42})

    assert changeset.valid?
  end
end
```

### PR DESCRIPTION
**Pull request by randycoulman**
Fixes  #57

Ecto.Schema has a typespec that looks like this:

```elixir
 schema() :: %{
  optional(atom()) => any(),
  :__struct__ => atom(),
  :__meta__ => Ecto.Schema.Metadata.t()
}
```

Because of the `__struct__` key, it looks like a struct, but really isn't and that was causing a `CaseClauseError` when trying to type-check an Ecto.Changeset.t() (which has a `schema()` inside of it.

This change adds a case clause that matches this case and then recursively ensures that the value of the `__struct__` key matches the specified type and that the rest of the fields also match the rest of the type.

### CODE REVIEW

File: lib/hammox/type_engine.ex [hunk 1]
```diff
@@ -352,6 +352,22 @@ defmodule Hammox.TypeEngine do
...
+
+          {:ok, error} ->
+            error
+
+          {error, :ok} ->
+            error
+
+          {{:error, struct_reasons}, {:error, rest_reasons}} ->
+            {:error, struct_reasons ++ rest_reasons}
+        end
```
Comment (msz) [inline lib/hammox/type_engine.ex:370]: Hammox only ever really returns one type error reason — the "reasons" array is more like a "reason stacktrace". So we can't concat two — if you look at the error message from the `"fail with incorrect __struct__ and fields"` test, you'll see this:
```
     ** (Hammox.TypeMatchError) 
     Returned value %{__struct__: "wrong type", key: "not a number"} does not match type %{__struct__: atom(), key: number()}.
       Value "wrong type" does not match type atom().
         Map value "not a number" for key :key does not match map value type number().
           Value "not a number" does not match type integer() | float().
```
The first 2 lines are from the first error, the last 2 lines are from the second, but they are going to be formatted like one stacktrace.

We could simplify to the following:
```suggestion
        with :ok <- match_type(struct_name, struct_type),
             :ok <-
               match_type(Map.delete(value, :__struct__), {:type, 0, :map, rest_field_types}),
             do: :ok
        end
```

**Review by msz — CHANGES_REQUESTED** [review]
Superb work!! And sorry for taking so long to get around to fixing this issue...

Just one small thing, but otherwise it looks great!

File: lib/hammox/type_engine.ex (hunk 1 above)
Comment (randycoulman) [reply lib/hammox/type_engine.ex]: Ah, interesting, OK! I mis-read some of the clauses here that used `reduce`; there was nothing quite like this case to base it on that I could find.

Change is made in 40225d2; let me know if I need to fix anything else!

**Review by msz — APPROVED** [review]
